vich_uploader:
    db_driver: orm

    mappings:
        partners:
            uri_prefix: /images/partners
            upload_destination: '%kernel.project_dir%/public/images/partners'
            delete_on_update:   true
            delete_on_remove:   true

        jobs:
            uri_prefix: /images/jobs
            upload_destination: '%kernel.project_dir%/public/images/jobs'

        comments:
            uri_prefix: /images/comments
            upload_destination: '%kernel.project_dir%/public/images/comments'

