vich_uploader:
    db_driver: orm

    mappings:
        partners:
            uri_prefix: /images/partners
            upload_destination: '%kernel.project_dir%/public/images/partners'
            inject_on_load: false
            delete_on_remove: false
            delete_on_update: false


        jobs:
            uri_prefix: /images/jobs
            upload_destination: '%kernel.project_dir%/public/images/jobs'
            inject_on_load: false
            delete_on_remove: false
            delete_on_update: false


        comments:
            uri_prefix: /images/comments
            upload_destination: '%kernel.project_dir%/public/images/comments'
            inject_on_load: false
            delete_on_remove: false
            delete_on_update: false
