vich_uploader:
    db_driver: orm

    mappings:
        partners:
            uri_prefix: /images/partners
            upload_destination: '%kernel.project_dir%/public/images/partners'

        jobs:
            uri_prefix: /images/jobs
            upload_destination: '%kernel.project_dir%/public/images/jobs'

        comments:
            uri_prefix: /images/comments
            upload_destination: '%kernel.project_dir%/public/images/comments'

        company:
            uri_prefix: /images/companies
            upload_destination: '%kernel.project_dir%/public/images/companies'

